apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api
  labels:
    app: catalog-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog-api
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      containers:
      - name: catalog-api
        image: rodrigosiqsilva/catalog-api:latest 
        ports:
        - containerPort: 4040
        - containerPort: 4041
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://+:4040;https://+:4041"
        - name: Kafka__BootstrapServers
          value: "kafka-service:29092"
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-api-service
spec:
  selector:
    app: catalog-api
  ports:
  - name: http
    port: 4040
    targetPort: 4040
  - name: https
    port: 4041
    targetPort: 4041
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
  labels:
    app: user-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
      - name: user-api
        image: rodrigosiqsilva/user-api:latest
        ports:
        - containerPort: 7070
        - containerPort: 7071
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://+:7070;https://+:7071"
        - name: Kafka__BootstrapServers
          value: "kafka-service:29092"
---
apiVersion: v1
kind: Service
metadata:
  name: user-api-service
spec:
  selector:
    app: user-api
  ports:
  - name: http
    port: 7070
    targetPort: 7070
  - name: https
    port: 7071
    targetPort: 7071