apiVersion: v1
kind: ConfigMap
metadata:
  name: user-api-configmap
data:
  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__Microsoft.AspNetCore: "Warning"
  KafkaConfig__BootstrapServers: "kafka-service:29092"
  KafkaConfig__TopicNameUserCreated: "user-created-topic"
  KafkaConfig__TopicNamePaymentProcessed: "payment-processed-topic"
  KafkaConfig__TopicNameOrderPlaced: "order-placed-topic"
  KafkaConfig__GroupId: "user-api-group"
  AllowedHosts: "*"
  ApiSettings__BaseUrl: "https://localhost:7047"
  ApiSettings__LoginEndpoint: "/Login"
  ApiSettings__UserEndpoint: "/api/User/"
---
apiVersion: v1
kind: Secret
metadata:
  name: user-api-secret
type: Opaque
data:
  ApiSettings__Credentials__Email: YmViZXRvQGhvdG1haWwuY29t
  ApiSettings__Credentials__Senha: Um9kcmlnb1NlbmhhJDIwMg==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-api-configmap
data:
  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__Microsoft.Hosting.Lifetime: "Information"
  KafkaConfig__BootstrapServers: "kafka-service:29092"
  KafkaConfig__TopicNamePaymentProcessed: "payment-processed-topic"
  KafkaConfig__GroupId: "catalog-api-group"
  ApiSettings__BaseUrl: "https://localhost:7094/"
  ApiSettings__BibliotecaEndpoint: "api/BibliotecaUsuario"
  ApiSettings__OrderEndpoint: "api/Order/"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-ws-configmap
data:
  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__Microsoft.Hosting.Lifetime: "Information"
  KafkaConfig__BootstrapServers: "kafka-service:29092"
  KafkaConfig__TopicNameUserCreated: "user-created-topic"
  KafkaConfig__TopicNamePaymentProcessed: "payment-processed-topic"
  KafkaConfig__GroupIdUserCreated: "user-api-group"
  KafkaConfig__GroupIdPaymentProcessed: "payment-api-group"
  Smtp__Server: "smtp.gmail.com"
  Smtp__Port: "587"
---
apiVersion: v1
kind: Secret
metadata:
  name: notification-ws-secret
type: Opaque
data:
  Smtp__Username: ZmlhcGNsb3VkZ2FtZXM1QGdtYWlsLmNvbQ==
  Smtp__Password: aGZvbbyBoYW1hIGRzc3ggZmV6dQ==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-ws-configmap
data:
  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__Microsoft.Hosting.Lifetime: "Information"
  KafkaConfig__BootstrapServers: "kafka-service:29092"
  KafkaConfig__TopicNameUserCreated: "user-created-topic"
  KafkaConfig__TopicNamePaymentProcessed: "payment-processed-topic"
  KafkaConfig__TopicNameOrderPlaced: "order-placed-topic"
  KafkaConfig__GroupId: "user-api-group"
  ApiSettings__BaseUrl: "https://localhost:7094/"
  ApiSettings__BibliotecaEndpoint: "api/BibliotecaUsuario"
  ApiSettings__OrderEndpoint: "api/Order/"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-ws-configmap
data:
  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__Microsoft.AspNetCore: "Warning"
  KafkaConfig__BootstrapServers: "kafka-service:29092"
  KafkaConfig__TopicNameUserCreated: "user-created-topic"
  KafkaConfig__TopicNamePaymentProcessed: "payment-processed-topic"
  KafkaConfig__TopicNameOrderPlaced: "order-placed-topic"
  AllowedHosts: "*"
  Jwt__Issuer: "FCG"
---
apiVersion: v1
kind: Secret
metadata:
  name: payment-ws-secret
type: Opaque
data:
  Jwt__Key: ZDgyZTExMTItNjZkYy00ZWQ2LTgyNzctYmNmZWEyYWFiMDJk