apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-ws
  labels:
    app: catalog-ws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-ws
  template:
    metadata:
      labels:
        app: catalog-ws
    spec:
      containers:
      - name: catalog-ws
        image: rodrigosiqsilva/catalog-ws:latest
        env:
        - name: DOTNET_ENVIRONMENT
          value: "Production"
        - name: Kafka__BootstrapServers
          value: "kafka-service:29092"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-ws
  labels:
    app: notification-ws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-ws
  template:
    metadata:
      labels:
        app: notification-ws
    spec:
      containers:
      - name: notification-ws
        image: rodrigosiqsilva/notification-ws:latest
        env:
        - name: DOTNET_ENVIRONMENT
          value: "Production"
        - name: Kafka__BootstrapServers
          value: "kafka-service:29092"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-ws
  labels:
    app: payment-ws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-ws
  template:
    metadata:
      labels:
        app: payment-ws
    spec:
      containers:
      - name: payment-ws
        image: rodrigosiqsilva/payment-ws:latest
        env:
        - name: DOTNET_ENVIRONMENT
          value: "Production"
        - name: Kafka__BootstrapServers
          value: "kafka-service:29092"